package com.swengsol;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class TemplateServlet extends HttpServlet {
  private static final long serialVersionUID = 1L;

  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
    PrintWriter out = response.getWriter();
    String copyright = "&copy; 2009, Software Engineering Solutions, Inc.";
    String bannerType = (String)request.getParameter("bannerType");

    if (null == bannerType)
      bannerType = (String)request.getAttribute("bannerType");
    if(bannerType != null) {
      if (bannerType.equalsIgnoreCase("header")) {
        out.println("<a href=\"index.html\">");
        out.println("Return</a><p />");
        out.print(getServletContext().getServletContextName());
        out.print(" [header generated by " + getServletName() + "]");
        out.print("<hr />");
      } else if (bannerType.equalsIgnoreCase("footer")) {
        out.print("<hr />");
        out.print(copyright);
        out.print(" (all rights reserved) <br />");
      } else if (bannerType.equalsIgnoreCase("file")) {
        String resourceName = (String)request.getParameter("resource");
        if (null != resourceName)
          request.getRequestDispatcher(resourceName).include(request, response);
      } else {
        out.print("Default template? <br />");
      }
    } else {
      out.print("!!!no banner type specified!!! <br />");
    }
  }
}
